### ISSUE TITLE
Auto-uninstall not working

### ISSUE THREAD

**Issue by N8Solutions** [TLWebdesign/Joomla-3-EOL-Security-Fixes#3]
Thank you very much for putting this together. It's greatly appreciated!

Just wanted to mention that at the end of the installation there is a message that says:

> After applying the fix it auto-uninstalls itself.

However, it is still present after installation.
Not a big deal as I can uninstall it myself, just wanted to mention it.

### EDIT

> [!NOTE]
> In the process of making the post for this issue, I installed it again so I could get the correct text at the end of the installation. I went back to uninstall it and it was in fact uninstalled. So upon the initial installation it was still there but a second installation on top removed it.

![image](https://github.com/TLWebdesign/Joomla-3-EOL-Security-Fixes/assets/12389693/a37b465d-8834-4f3c-9485-5139d5f76047)

**Comment by TLWebdesign** [comment]
I just released a fix. Thanks for reporting!
