### ISSUE TITLE
Array dumping in search module

### ISSUE THREAD

**Issue by jflash** [TLWebdesign/Joomla-3-EOL-Security-Fixes#6]
Hello!

Release 1.0.6 has in file Joomla-3-EOL-Security-Fixes/files/components/com_search/views/search/view.html.php on line 47:
var_dump($areas);
This prints unnecessary code :)

**Comment by TLWebdesign** [comment]
Oh wow that's a stupid mistake. Thanks for reporting. I've just fixed it and released a new version 1.0.7
